spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    ufrn.imd.ApiGateway: DEBUG