spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888

management:
  endpoint:
    web:
      exposure:
        include: "refresh"
        
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    ufrn.imd.ApiGateway: DEBUG